import { useState } from 'react';
import { ArrowUpRight, ArrowDownLeft, ArrowRight, Plus, Download, Building2, Receipt, Users, Wallet, CalendarDays } from 'lucide-react';
import type { FullDatabaseState } from '../utils/guardRails';
import type { NavigationTab } from './layout/Sidebar';
import type { PurchaseDetail } from '../types';
import { formatCurrency, formatDate } from '../utils/calculations';
export function cashRows(db:FullDatabaseState) {
 return [...db.payments.map(p=>({id:`OR ${p.orderreceipt}`,date:p.dateofpayment,name:p.paidbyName,category:'Collections',amount:p.totalamount,tab:'payment' as NavigationTab})),...db.expenses.map(e=>({id:`EXP-${e.id}`,date:e.daterelease,name:e.description,category:e.purpose||'Operating expense',amount:-e.amount,tab:'expenses' as NavigationTab}))].sort((a,b)=>b.date.localeCompare(a.date));
}
function exportRows(rows:ReturnType<typeof cashRows>) {
 const quote=(v:unknown)=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';
 const csv=[['Reference','Date','Description','Category','Cash inflow','Cash outflow'],...rows.map(r=>[r.id,r.date,r.name,r.category,Math.max(r.amount,0),Math.max(-r.amount,0)])].map(r=>r.map(quote).join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='JLD-cash-flow.csv';a.click();URL.revokeObjectURL(url);
}
export function AccountantWorkspace({db,onNavigate,onPayment,onContract,onSOA,report=false}:{db:FullDatabaseState;onNavigate:(tab:NavigationTab)=>void;onPayment:()=>void;onContract:()=>void;onSOA:(p:PurchaseDetail)=>void;report?:boolean}) {
 const [month,setMonth]=useState('all'); const [query,setQuery]=useState('');
 const all=cashRows(db); const months=[...new Set(all.map(r=>r.date.slice(0,7)))].sort().reverse();
 const rows=all.filter(r=>(month==='all'||r.date.startsWith(month))&&`${r.name} ${r.id} ${r.category}`.toLowerCase().includes(query.toLowerCase()));
 const periodRows=all.filter(r=>month==='all'||r.date.startsWith(month));
 const inflow=periodRows.reduce((s,r)=>s+Math.max(0,r.amount),0),outflow=periodRows.reduce((s,r)=>s+Math.max(0,-r.amount),0);
 const contracts=db.leads.filter(p=>p.status==='active');const pending=db.payrollRecords.filter(p=>p.status==='active'&&p.approvalStatus==='Pending');
 const due=contracts.filter(p=>p.duedate.slice(0,10)<=new Date().toLocaleDateString('en-CA')&&p.leadStatus!=='Fully Paid').sort((a,b)=>a.duedate.localeCompare(b.duedate));
 const workflow:[string,string,NavigationTab][]=[['01','Properties & lots','products'],['02','Buyers & contracts','contracts'],['03','Collections','payment'],['04','Commissions','agents-commissions'],['05','Cash flow','reports']];
 return <div className={report?"accounting-page finance-records":"accounting-page"}><div className="page-heading"><div><div className="eyebrow">{report?'FINANCIAL REPORTING':'YOUR ACCOUNTING WORKSPACE'}</div><h1>{report?'Cash flow & reports':'Business overview'}</h1><p>{report?'Trace every recorded cash movement back to its source.':'A clear view of your properties, collections, and next steps.'}</p></div><div className="page-actions"><button className="secondary-button" onClick={()=>exportRows(rows)}><Download size={17}/> Export {report?'CSV':'cash flow'}</button><button className="primary-button" onClick={onPayment}><Plus size={18}/> Record payment</button></div></div>
 <div className="period-toolbar"><span><span className="live-dot"/> Connected to workspace records</span><label><CalendarDays size={16}/><select aria-label="Reporting period" value={month} onChange={e=>setMonth(e.target.value)}><option value="all">All recorded dates</option>{months.map(m=><option key={m} value={m}>{new Date(m+'-01T12:00:00').toLocaleDateString('en-PH',{month:'long',year:'numeric'})}</option>)}</select></label></div>
 <div className="metric-grid">{[{label:'Cash collected',value:formatCurrency(inflow),note:'Recorded client payments',Icon:ArrowDownLeft,tab:'payment'},{label:'Cash disbursed',value:formatCurrency(outflow),note:'Recorded expense vouchers',Icon:ArrowUpRight,tab:'expenses'},{label:'Net cash movement',value:formatCurrency(inflow-outflow),note:'Collections less disbursements',Icon:Wallet,tab:'reports'},{label:'Active contracts',value:String(contracts.length),note:`Across ${db.products.filter(p=>p.status==='active').length} property projects`,Icon:Building2,tab:'contracts'}].map((m,i)=><button key={m.label} className={`metric-card metric-${i}`} onClick={()=>onNavigate(m.tab as NavigationTab)}><div><span>{m.label}</span><m.Icon size={19}/></div><strong>{m.value}</strong><small>{m.note}</small></button>)}</div>
 {!report&&<><section className="workflow-panel"><div className="section-heading"><div><h2>From property to payment</h2><p>Follow the connected sales workflow.</p></div><button className="text-button" onClick={onContract}>New contract <Plus size={16}/></button></div><div className="workflow-steps">{workflow.map(([n,label,tab],i)=><button key={tab} onClick={()=>onNavigate(tab)}><span>{n}</span><strong>{label}</strong>{i<workflow.length-1&&<ArrowRight size={16}/>}</button>)}</div></section><div className="overview-columns"><section className="surface"><div className="section-heading"><div><h2>Needs your attention</h2><p>Start with the work that moves today forward.</p></div><span className="count-badge">{due.length+pending.length}</span></div><button className="attention-row" onClick={()=>onNavigate('contracts')}><span className="attention-icon amber"><Receipt size={20}/></span><div><strong>{due.length} contracts to review</strong><small>Due dates reached · check account statements</small></div><ArrowUpRight size={18}/></button><button className="attention-row" onClick={()=>onNavigate('payroll')}><span className="attention-icon blue"><Users size={20}/></span><div><strong>{pending.length} payroll records pending</strong><small>Review calculations before approval</small></div><ArrowUpRight size={18}/></button><button className="attention-row" onClick={()=>onNavigate('agents-commissions')}><span className="attention-icon green"><Wallet size={20}/></span><div><strong>{formatCurrency(db.agents.filter(a=>a.status==='active').reduce((s,a)=>s+a.balance,0))} commission balance</strong><small>Review agent balances and releases</small></div><ArrowUpRight size={18}/></button></section><section className="surface"><div className="section-heading"><div><h2>Cash movement</h2><p>Based on the selected reporting period</p></div><span className="currency-chip">PHP</span></div><div className="cash-visual">{[['Collections',inflow,'inflow'],['Disbursements',outflow,'outflow']].map(([label,value,cls])=><div key={label}><div><span>{label}</span><strong>{formatCurrency(Number(value))}</strong></div><div className="bar-track"><div className={String(cls)} style={{width:`${Number(value)/Math.max(inflow,outflow,1)*100}%`}}/></div></div>)}</div><div className="cash-footnote">Payroll approvals and unpaid commissions are not cash movements. Released vouchers appear in expenses.</div></section></div></>}
 <section className="surface ledger"><div className="section-heading"><div><h2>{report?'Cash transaction ledger':'Recent transactions'}</h2><p>{report?'Includes archived receipts and vouchers; archiving does not reverse cash. No opening balance assumed.':'Collections and disbursements in one place.'}</p></div>{report?<input aria-label="Search cash transactions" placeholder="Search reference or description…" value={query} onChange={e=>setQuery(e.target.value)}/>:<button className="text-button" onClick={()=>onNavigate('reports')}>View all transactions <ArrowRight size={16}/></button>}</div><div className="table-scroll"><table><thead><tr><th>Reference / date</th><th>Description</th><th>Source</th><th className="amount">Amount</th><th>Record</th></tr></thead><tbody>{(report?rows:rows.slice(0,5)).map(r=><tr key={r.id}><td><strong>{r.id}</strong><small>{formatDate(r.date)}</small></td><td>{r.name}</td><td><span className={`source-pill ${r.amount>=0?'green':'neutral'}`}>{r.category}</span></td><td className={`amount ${r.amount>=0?'positive':''}`}>{r.amount>=0?'+':'−'}{formatCurrency(Math.abs(r.amount))}</td><td><button className="text-button" onClick={()=>onNavigate(r.tab)}>Open <ArrowUpRight size={15}/></button></td></tr>)}{!rows.length&&<tr><td colSpan={5} className="empty-state">No cash transactions for this selection.</td></tr>}</tbody></table></div></section>
 {report&&<section className="surface"><div className="section-heading"><div><h2>Buyer statements of account</h2><p>Select the exact contract to review its payment history.</p></div></div><div className="table-scroll"><table className="record-table"><thead><tr><th>Buyer</th><th>Property</th><th>Block</th><th>Lot</th><th>Statement</th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td><strong>{c.clientName}</strong></td><td>{c.productCode}</td><td>{c.blockno}</td><td>{c.lotno}</td><td><button className="table-action" onClick={()=>onSOA(c)}>View statement</button></td></tr>)}{!contracts.length&&<tr><td colSpan={5}>No active contracts.</td></tr>}</tbody></table></div></section>}
 <footer className="page-footnote">JLD Subdivision <span>•</span> Philippine Peso (PHP) <span>•</span> Demo workspace — changes last for this session</footer></div>
}



