<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>RealProperty</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <AppConfig>app.config</AppConfig>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GenerateResourceUsePreserializedResources>True</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="RealProperty.Report1.rdlc" />
    <None Remove="RealProperty.Reports.rptAll_Payslips.rdlc" />
    <None Remove="RealProperty.Reports.rptlistofexpenses.rdlc" />
    <None Remove="RealProperty.Reports.rptpaymenthistory.rdlc" />
    <None Remove="RealProperty.Reports.rptPayroll.rdlc" />
    <None Remove="RealProperty.Reports.rptSOA.rdlc" />
    <None Remove="RealProperty.Reports.rptstatementofcashflow.rdlc" />
    <EmbeddedResource Include="RealProperty.Report1.rdlc" LogicalName="RealProperty.Report1.rdlc" />
    <EmbeddedResource Include="RealProperty.Reports.rptAll_Payslips.rdlc" LogicalName="RealProperty.Reports.rptAll_Payslips.rdlc" />
    <EmbeddedResource Include="RealProperty.Reports.rptlistofexpenses.rdlc" LogicalName="RealProperty.Reports.rptlistofexpenses.rdlc" />
    <EmbeddedResource Include="RealProperty.Reports.rptpaymenthistory.rdlc" LogicalName="RealProperty.Reports.rptpaymenthistory.rdlc" />
    <EmbeddedResource Include="RealProperty.Reports.rptPayroll.rdlc" LogicalName="RealProperty.Reports.rptPayroll.rdlc" />
    <EmbeddedResource Include="RealProperty.Reports.rptSOA.rdlc" LogicalName="RealProperty.Reports.rptSOA.rdlc" />
    <EmbeddedResource Include="RealProperty.Reports.rptstatementofcashflow.rdlc" LogicalName="RealProperty.Reports.rptstatementofcashflow.rdlc" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="Microsoft.ReportViewer.WinForms" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Configuration" />
    <Reference Include="MySql.Data">
      <HintPath>MySql.Data.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Data">
      <HintPath>..\..\..\..\..\..\..\..\..\..\windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.Winforms" Version="150.1652.0" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.11" />
  </ItemGroup>
</Project>
